extends:
  - eslint:recommended
  - plugin:prettier/recommended

parserOptions:
  ecmaVersion: 2017
  sourceType: script

env:
  es6: true
  commonjs: true

rules:
  # prefer-const: error
  # no-var: error
  strict: ["error", "global"]
  no-useless-escape: 0
  valid-jsdoc: [2, {requireReturn: false, requireReturnDescription: false}]
