sudo: false

language: node_js

node_js:
  - '7'
  - '8'
  - '9'

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules

before_script: lerna bootstrap

script:
  - lerna run test
  - lerna run benchmark
